[build]
  command = "npm --prefix web run build"
  publish = "web/dist"
  functions = "netlify/functions"

[dev]
  command = "npm --prefix web run dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200